version: '3.9'
services:
  # frontend: 
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '3000:5173'
  #   volumes:
  #     - ./client:/usr/app
  #     - /usr/app/build
  #     - /usr/app/node_modules
    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules

